global using MediatR;
global using Carter;
global using Mapster;
global using BuildingBlockks.CQRS;
global using CatalogAPI.Models;
global using Marten;
global using FluentValidation;
global using BuildingBlockks.Behaviors;
global using BuildingBlockks.Exceptions.Handler;